server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    username: zelmi
    url: jdbc:sqlserver://localhost:1433;encrypt=false;databaseName=db_zelmi
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: Handboll8
  jpa:
    show-sql: 'true'
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
